### ISSUE TITLE
How to get single-cell Hi-C data from Li2019's data on GEO

### ISSUE THREAD

**Issue by lhqxinghun** [lixiaoms/TOKI#1]
Hello,
  Thank you for developing deTOKI which can identify TAD-like domains effectively from single-cell Hi-C data, I think it will bring new insight in investigating the biological meaning of TAD at single-cell level.
  I have noticed that you have used the single-cell Hi-C data from Li2019's data (GSE 119171 on GEO) and called TAD-like domains on it (Fig. 5c and Additional file 5(https://static-content.springer.com/esm/art%3A10.1186%2Fs13059-021-02435-7/MediaObjects/13059_2021_2435_MOESM5_ESM.csv)). I am also interested in this dataset and want to get single-cell Hi-C data of each cell from it. However, I find the GSE119171 on GEO only contains a "GSE119171_JL.merged.sorted.nodup.long.juice.q30.hic" and a "GSE119171_RAW.tar". The former seems to be bulk Hi-C not for single-cell Hi-C of each cell, and the latter only contains methylation data. So I have problems in getting single-cell Hi-C data (Hi-C matrix or its sparsed format) from the GSE119171. Would you please kindly tell me how to get it.
  Thank you!

**Comment by lixiaoms** [comment]
Thank you for your question. Sorry for the delayed response.
I got the Li2019's single-cell contact matrix data by email the first author, Li.
Good luck.
